islandora_citations.islandora_citations.*:
  type: config_entity
  label: islandora_citations
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    csl:
      type: text

field.widget.third_party.islandora_citations:
  type: mapping
  mapping:
    csl_name:
      type: string
      label: Name of CSL
    field_name:
      type: string
      label: Name of Field
